package com.example.pwd_app.model

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "RegisteredSchoolsTable")
data class RegisteredSchools(
    @PrimaryKey val id: String,
    val school_name: String? = "",
    val taluka: String? = "",
    val district: String? = "",
    val atc_office: String? = "",
    val po_office: String? = "",
    val location_lat: String? = "",
    val location_long: String? = "",
    val schoolstartdate: String? = "",
    val schooltype: String? = "",
    val schoolconstructionyear: String? = "",
    val lastrepairingyear: String? = "",
    val rentedname: String? = "",
    val rentedrupees: String? = "",
    val constructiontype: String? = "",
    val securitywall: String? = "",
    val sanctioned_class: String? = "",
    val sanctioned_boys: String? = "",
    val sanctioned_girls: String? = "",
    val sanctioned_total: String? = "",
    val onrollboys: String? = "",
    val onrollgirls: String? = "",
    val academicyear: String? = "",
    val landArea: String? = "",
    val unpavedArea: String? = "",
    val pavedArea: String? = "",
    val sourceofwater: String? = "",
    val schoolhead: String? = "",
    val requiredtoiletgirls: String? = "",
    val requiredtoiletboys: String? = "",
    val requiredbathgirls: String? = "",
    val requiredbathboys: String? = "",
    val staffquarters: String? = "",
    val kitchen: String? = "",
    val playground: String? = "",
    val securitywalllength: String? = "",
    val wallcondition: String? = "",
    val dateofcons: String? = "",
    val cctvavailable: String? = "",
    val cctvno: String? = "",
    val playgroundareatype: String? = "",
    val internalroadavailable: String? = "",
    val availableRoadLength: String? = "",
    val materialroad: String? = "",
    val libraryavailble: String? = "",
    val librarycondtn: String? = "",
    val stafffquartersquantity: String? = "",
    val availabletoiletgirls: String? = "",
    val conditionoftoiletgirls: String? = "",
    val availabletoiletboys: String? = "",
    val conditionoftoiletboys: String? = "",
    val availablebathroomgirls: String? = "",
    val conditionofbathroomgirls: String? = "",
    val availablebathroomboys: String? = "",
    val conditionofbathroomboys: String? = "",
    val StaffQuantity: String? = "",
    val PrincipalQtr: String? = "",
    val TypeOneQtrClsFour: String? = "",
    val TypeTwoQtrClsThree: String? = "",
    val EntryBy: String? = "",
    val EntryByPost: String? = "",
    val UploadDate: String? = "",
    val UploadTime: String? = ""
)
